---
- hosts: "{{ NODE_GROUP }}"
  tasks:
    - name: staking create-validator
      shell: $HOME/go/bin/blzcli tx staking create-validator --amount=1990000000ubnt --pubkey=$($HOME/go/bin/blzd tendermint show-validator) --moniker={{ validator }} --commission-rate=0.1 --commission-max-rate=0.2 --commission-max-change-rate=0.01 --min-self-delegation=1 --gas=auto --gas-adjustment=1.2 --gas-prices=10.0ubnt --from vuser -y
      register: create_validator

    - debug:
        var: create_validator.stdout_lines
